### ISSUE TITLE
GL-003 Investigate ev charger APIs

### ISSUE THREAD

**Issue by Thordijk95** [AlexandrosKakotaritis/GroenLoad#3]
Request Eco movement if there is a possibility for free access to the api limited to the Nedap campus. 
Or a reduced fee, as we will only be looking at the Nedap campus.

**Comment by AlexandrosKakotaritis** [comment]
![Image](https://github.com/AlexandrosKakotaritis/GroenLoad/assets/149692612/85927e83-8e26-4a9c-889d-91e6ba5bd47e)
